version: "3.9"

services:
  caddy-rss_temple_home:
    image: caddy:2
    ports:
      - "3000:3000"
    volumes:
      - caddy_data:/data/
      - caddy_config:/config/
      - caddy_srv:/srv/
  rss_temple_home:
    volumes:
      - caddy_srv:/srv/
volumes:
  caddy_data:
  caddy_config:
  caddy_srv:
