version: "3.9"

services:
  caddy-rss_temple_home:
    image: caddy:2
    ports:
      - "3000:3000"
    volumes:
      - caddy_data:/data/
      - caddy_config:/config/
      - caddy_srv:/srv/
  rss_temple_home:
    command: >
      ash -c "
        [ \"$$(ls -A /srv/)\" ] || echo '<html><body><h1>Building Site...</h1></body></html>' > /srv/index.html
        yarn run build

        rm -rf /srv/* && cp -R /build/_site/* /srv/

        while :; do
          sleep 3600
        done
      "
    volumes:
      - caddy_srv:/srv/
volumes:
  caddy_data:
  caddy_config:
  caddy_srv:
