version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_app_latest:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - build_app_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build_home_latest:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - build_home_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test_app

jobs:
  build_app_latest:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple/
          command: docker build -t rss_temple_app:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_app:latest $DOCKER_USERNAME/rss_temple_app:latest
            docker push $DOCKER_USERNAME/rss_temple_app:latest

  build_app_tag:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple/
          command: docker build -t rss_temple_app:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_app:latest $DOCKER_USERNAME/rss_temple_app:$CIRCLE_TAG
            docker push $DOCKER_USERNAME/rss_temple_app:$CIRCLE_TAG

  build_home_latest:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple-home/
          command: docker build -t rss_temple_home:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_home:latest $DOCKER_USERNAME/rss_temple_home:latest
            docker push $DOCKER_USERNAME/rss_temple_home:latest

  build_home_tag:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple-home/
          command: docker build -t rss_temple_home:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_home:latest $DOCKER_USERNAME/rss_temple_home:$CIRCLE_TAG
            docker push $DOCKER_USERNAME/rss_temple_home:$CIRCLE_TAG

  test_app:
    docker:
      - image: cimg/node:16.20-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "rss-temple/yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install --frozen-lockfile
          working_directory: rss-temple/
      - save_cache:
          key: dependency-cache-{{ checksum "rss-temple/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: setup-test-environment
          command: |
            yarn generate-licenses-file
          working_directory: rss-temple/
      - run:
          name: angular-test
          command: yarn run cross-env TEST_TYPE=xml ng test --code-coverage --no-watch --no-progress
          working_directory: rss-temple/
      - store_test_results:
          path: rss-temple/test-results/
      - store_artifacts:
          path: rss-temple/test-results/
      - run:
          name: codecov
          command: yarn run codecov --disable=gcov
          working_directory: rss-temple/
