version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_web_app_latest:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - build_web_app_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build_home_latest:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - build_home_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test_web_app

orbs:
  browser-tools: circleci/browser-tools@1.4.6
  codecov: codecov/codecov@3.3.0

jobs:
  build_web_app_latest:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple-web-app/
          command: docker build -t rss_temple_web_app:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_web_app:latest $DOCKER_USERNAME/rss_temple_web_app:latest
            docker push $DOCKER_USERNAME/rss_temple_web_app:latest

  build_web_app_tag:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple-web-app/
          command: docker build -t rss_temple_web_app:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_web_app:latest $DOCKER_USERNAME/rss_temple_web_app:$CIRCLE_TAG
            docker push $DOCKER_USERNAME/rss_temple_web_app:$CIRCLE_TAG

  build_home_latest:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple-home/
          command: docker build -t rss_temple_home:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_home:latest $DOCKER_USERNAME/rss_temple_home:latest
            docker push $DOCKER_USERNAME/rss_temple_home:latest

  build_home_tag:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          working_directory: rss-temple-home/
          command: docker build -t rss_temple_home:latest .
      - run:
          name: Docker Upload
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag rss_temple_home:latest $DOCKER_USERNAME/rss_temple_home:$CIRCLE_TAG
            docker push $DOCKER_USERNAME/rss_temple_home:$CIRCLE_TAG

  test_web_app:
    docker:
      - image: cimg/node:16.20-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "rss-temple-web-app/yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install --frozen-lockfile
          working_directory: rss-temple-web-app/
      - save_cache:
          key: dependency-cache-{{ checksum "rss-temple-web-app/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: setup-test-environment
          command: |
            yarn generate-licenses-file
            cp src/environments/environment.dev.ts src/environments/environment.ts
          working_directory: rss-temple-web-app/
      - run:
          name: angular-test
          command: yarn cross-env TEST_TYPE=xml ng test --code-coverage --no-watch --no-progress
          working_directory: rss-temple-web-app/
      - store_test_results:
          path: rss-temple-web-app/test-results/
      - store_artifacts:
          path: rss-temple-web-app/test-results/
      - codecov/upload
