services:
  rss_temple_web_app:
    ports:
      - '4200:4200'
    volumes:
      - caddy_data:/data/
      - caddy_config:/config/
    networks:
      - default
      - rss_temple_web_app_net
volumes:
  caddy_data:
  caddy_config:
networks:
  rss_temple_web_app_net:
    internal: true
